### ISSUE TITLE
Onboarding flow improvements

### ISSUE THREAD

**Issue by StanevPrime** [Prime-Holding/rx_bloc#932]
As a user I want to have an improved version of the onboarding flow

ACs

- [x]  RxUnfocuser should be added to the first registration step (email and password)
- [x]  The bottom navigation bar shadow looks off
<img width="411" alt="Image" src="https://github.com/user-attachments/assets/c7cea1f1-b1bf-4339-a0cc-82c8da238896" />

~- [ ]  The OTP is not cleared out after wrong code is entered and the field it gets disabled after some period, which makes it unusable and the flow is blocked~
- [ ]  The back button on the Confirm email page leads to the landing page, instead of the Register page (first step)
- [x]  There is some delay after the submit button is pressed and the loading animation appears in the phone page
- [x]  There is some delay after the OPT is entered and the loading appears in the confirm phone page
- [x]  There is form behaviour inconsistency between the first page of the registration flow and the phone page. In the first page the button is always enabled, while in the phone page it gets enabled once the phone becomes valid. Let's stick to the behaviour of the first page of the registration, since it's same as on the login page.
- [x]  The "Don't have an account? Sign up!" text button does not have enough padding. Please stick to the default button padding to ensure accessibility.
- [x] When mocking the email onboarding with error, the user is able to pull down modal bottom sheet and proceed to the phone onboarding
- [x] Clicking "Retry" button multiple times opens a new bottom sheet each time
- [x] Setting `enable-feature-onboarding` flag should also force-enable:
  - Deep linking
  - Login
- [x] The enter phone number page needs to be redesigned as well as the validation behaviour (use the attached screenshot as inspiration)
<img width="509" alt="Image" src="https://github.com/user-attachments/assets/93b95735-0e95-4cd1-897f-7f2e939175ff" />

- Apply the following pattern to Register/Confirm Email/Email Confirmed/Enter Phone Pages 
  -  Icon
  - Header
  - Description
  - {Content}
  - Button
- Pages:
  - [x] Register (email/password) page
  - [x] Confirm Email page
  - [x] Email Confirmed page
  - [x] Phone number page
  - [x] Phone number confirm page

- [ ] The pin code is hidden behind the keyboard. Hint: a scroll view can be added similar on the register page
![Image](https://github.com/user-attachments/assets/f4e1bf6b-6014-470a-bd85-473f26021d97)

**Comment by JvnSlv** [comment]
When mocking the email onboarding with error, the user is able to pull down modal bottom sheet and proceed to the phone onboarding

https://github.com/user-attachments/assets/dd868473-30b2-41b7-9a1c-b3103c80b2fa

The modal bottom sheet appears to be under the bottom navigation bar, and part of it is obstructed by the shadow

![Image](https://github.com/user-attachments/assets/f01081a5-704b-4456-bb61-b54571cd7af1)

**Comment by GoranPrime** [comment]
"The back button on the Confirm email page leads to the landing page, instead of the Register page (first step)"

This was intentional, since when we first enter the Register page, it immediately redirects the user to the appropriate step if they've already started registration (has an access token).
If we do it the suggested way and the user presses back after getting redirected to Confirm email, they will be presented with a Register form again, and potentially start the flow to create a different account (or continue with the same one). Is this the intended behavior?

For now I'll change it to go back to Register page, but just wanted to double check

**Comment by StanevPrime** [comment]
> "The back button on the Confirm email page leads to the landing page, instead of the Register page (first step)"
> 
> This was intentional, since when we first enter the Register page, it immediately redirects the user to the appropriate step if they've already started registration (has an access token). If we do it the suggested way and the user presses back after getting redirected to Confirm email, they will be presented with a Register form again, and potentially start the flow to create a different account (or continue with the same one). Is this the intended behavior?
> 
> For now I'll change it to go back to Register page, but just wanted to double check

I see. Let's stick to the easier and less-problematic option. The UX can be improved in the actual project where the template is used.

**Comment by DDavidPrime** [comment]
> `There is some delay after the OPT is entered and the loading appears in the confirm phone page`

This is an artificial delay on the local server to simulate a real-world scenario. I can remove it, but it won't go away in apps that will be using this when communicating with BE.

> `The OTP is not cleared out after wrong code is entered and the field it gets disabled after some period, which makes it unusable and the flow is blocked`

I've checked but there's currently no way to reset a code in the OTP screen programatically. We may need to include this functionality as part of the `widget_toolkit_otp` before adding it to the onboarding flow.

@StanevPrime ^

**Comment by StanevPrime** [comment]
> > `There is some delay after the OPT is entered and the loading appears in the confirm phone page`
> 
> This is an artificial delay on the local server to simulate a real-world scenario. I can remove it, but it won't go away in apps that will be using this when communicating with BE.
> 
> > `The OTP is not cleared out after wrong code is entered and the field it gets disabled after some period, which makes it unusable and the flow is blocked`
> 
> I've checked but there's currently no way to reset a code in the OTP screen programatically. We may need to include this functionality as part of the `widget_toolkit_otp` before adding it to the onboarding flow.
> 
> @StanevPrime ^

`This is an artificial delay on the local server to simulate a real-world scenario. I can remove it, but it won't go away in apps that will be using this when communicating with BE.`

The artificial delay on the server-side needs to be represented with the appropriate loading state from the client-side.

`We may need to include this functionality as part of the `widget_toolkit_otp` before adding it to the onboarding flow.`

Feel free to create such ticket

**Comment by DDavidPrime** [comment]
The following ACs are blocked until [#151](https://github.com/Prime-Holding/widget_toolkit/issues/151) is resolved:
- `The OTP is not cleared out after wrong code is entered and the field it gets disabled after some period, which makes it unusable and the flow is blocked`
- `There is some delay after the OPT is entered and the loading appears in the confirm phone page`

**Comment by StanevPrime** [comment]
> The following ACs are blocked until [#151](https://github.com/Prime-Holding/widget_toolkit/issues/151) is resolved:
> 
> - `The OTP is not cleared out after wrong code is entered and the field it gets disabled after some period, which makes it unusable and the flow is blocked`
> 
> - `There is some delay after the OPT is entered and the loading appears in the confirm phone page`

I believe we can remove them from this ticket because they will be handled entirely from the widget toolkit otp package

**Comment by nikolay-vasilev-prime** [comment]
"The back button on the Confirm email page leads to the landing page, instead of the Register page (first step)" this one is still happening.

**Comment by DavidDWiser** [comment]
After a bit of testing I couldn't reproduce this issue. Closing...
